[general]
id = "sd1-ff00_0_110"
config_dir = "/share/conf"

[trust_db]
connection = "/share/cache/sd1-ff00_0_110.trust.db"

[path_db]
connection = "/share/cache/sd1-ff00_0_110.path.db"

[sd]
address = "0.0.0.0:30255"

[tracing]
enabled = false

[metrics]
prometheus = "0.0.0.0:30452"

[features]

[api]
addr = "0.0.0.0:30955"

[log.console]
level = "debug"
