services:
  prometheus:
    command:
    - --config.file
    - /prom-config/prometheus.yml
    container_name: prometheus
    image: prom/prometheus:v2.6.0
    network_mode: host
    volumes:
    - /home/jelte/GolandProjects/scion/gen:/prom-config:ro
version: '2.4'
